---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"
  - flowAnimation: &flow-slow
      thresholdOffValue: 2
      thresholdLwrValue: 10
      thresholdLwrDurationSecs: 1
      thresholdUprValue: 100
      thresholdUprDurationSecs: 0.1

#------------------------------------------------------------------------------
# Panel Config

test:
  testDataBaseOffset: 1
  
cellIdPreamble: "cell-"
gradientMode: "hue"
cells: 
  KAFKA:
    link:
      url: "https://app.diagrams.net/?p=svgdata"
    dataRef: "toalMsgKAFKA"
    label:
      separator: "cr"
      units: "short"
      unitsPostfix: "msg"
    labelColor:
      gradientMode: "hue"
      #thresholds:
        #- {color: "red", level: 0}
        #- {color: "green", level: 1}
    fillColor:
      thresholds:
        - {color: "semi-dark-red", level: 0}
        - {color: "semi-dark-green", level: 1}

  LogsAlgorilla:
    dataRef: "totalLogs"
    label:
      separator: "colon"
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "red", level: 0}
        - {color: "_", level: 1}

  AlertsAlgorilla:
    dataRef: "totalAlerts"
    label:
      separator: "colon"
      units: "short"
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "red", level: 0}
        - {color: "_", level: 1}

  Grafana:
    dataRef: "grafanaUp"
    label:
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "red", level: 0}
        - {color: "green", level: 1}

  AlertRules:
    link:
      url: "http://192.168.10.232:3000/d/LzldHAVnz/victoriametrics-vmalert"
    dataRef: "alertingRules"
    label:
      separator: "replace"
      units: "short"
      unitsPostfix: "Alerting Rules"
    labelColor:
      gradientMode: "hue"
      thresholds:
        #- {color: "red", level: 0}
        #- {color: "green", level: 1}

  ALERTMANAGER:
    link:
      url: "http://192.168.10.232:3000/d/4HhbN1BZk/zookeeper-exporter-dabealu"
    dataRef: "alertmanagerUp"
    label:
      separator: "colon"
      units: "short"
      unitsPostfix: "UP"
    labelColor:
      gradientMode: "hue"
      #thresholds:
        #- {color: "red", level: 0}
        #- {color: "green", level: 1}


  AlertsToCoraline:
    link:
      url: "http://192.168.10.232:3000/d/eea-9_sik/alertmanager"
    dataRef: "activeAlert"
    label:
      separator: "replace"
      units: "short"
      unitsPostfix: "Active Alerts"
    labelColor:
      gradientMode: "hue"
      thresholds:
        #- {color: "red", level: 0}
        #- {color: "green", level: 1}

  ZOOKEEPER:
    link:
      url: "http://192.168.10.232:3000/d/4HhbN1BZk/zookeeper-exporter-dabealu"
    dataRef: "zk_up"
    #label:
      #separator: "cr"
      #units: "short"
      #unitsPostfix: "(msg)"
    labelColor:
      gradientMode: "hue"
      #thresholds:
        #- {color: "red", level: 0}
        #- {color: "green", level: 1}
    fillColor:
      thresholds:
        - {color: "semi-dark-red", level: 0}
        - {color: "semi-dark-green", level: 1}

  CORALINE:
    link:
      url: "http://192.168.10.230:18630/"
    dataRef: "hbCoraline"
    label:
      separator: "space"
      units: "short"
      unitsPostfix: ")"
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "red", level: 0}
        - {color: "green", level: 1}
    fillColor:
      thresholds:
        - {color: "semi-dark-red", level: 0}
        - {color: "semi-dark-green", level: 1}
    #fillLevel:
      #thresholdLwrFillPercent: 100
      #thresholdUprFillPercent: 0
      #thresholdLwrValue: 0
      #thresholdUprValue: 1000
      f#illDirection: 'bottomToTop'

  ELK:
    link:
      url: "http://192.168.10.232:3000/d/n_nxrE_mk/elasticsearch"
    dataRef: "elk_cluster_status"
    label:
      #separator: "cr"
      #units: "short"
      #unitsPostfix: "(msg)"
    fillColor:
      thresholds:
        - {color: "semi-dark-green", level: 1}
        - {color: "semi-dark-yellow", level: 2}
        - {color: "semi-dark-red", level: 3}

  ELKdocs:
    dataRef: "totalELKdocs"
    label:
      separator: "replace"
      #units: "short"
      unitsPostfix: "docs"
    labelColor:
      gradientMode: "hue"
      #thresholds:
        #- {color: "red", level: 0}
        #- {color: "green", level: 1}

  VICTORIAMETRICS:
    link:
      url: "http://192.168.10.232:3000/d/4HhbN1BZk/zookeeper-exporter-dabealu"
    dataRef: "rateVM"
    label:
      separator: "replace"
      units: "short"
      unitsPostfix: "data/s"
      decimalPoints: 2
    fillColor:
      thresholds:
        - {color: "semi-dark-red", level: 0}
        - {color: "semi-dark-green", level: 2}

  ALERTS_OTHERS:
    dataRef: "alertsOtherSources"
    label:
      separator: "colon"
      units: "short"
      #unitsPostfix: "docs"
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "red", level: 0}
        - {color: "_", level: 1}

  LogsToCoraline:
    dataRef: "logsInput"
    label:
      separator: "colon"
      units: "short"
      #unitsPostfix: "docs"
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "red", level: 0}
        - {color: "_", level: 1}

  Dictionnaries:
    dataRef: "timeExecDict"
    label:
      separator: "cr"
      units: "short"
      unitsPostfix: "s (avg. exec time)"
      decimalPoints: 3
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "_", level: 0.000}
        - {color: "light-orange", level: 1.500}
        - {color: "light-red", level: 3.000}
