---

mappings:
  # Règle pour le STATUT de Kafka (couleur)
  - type: series-to-color
    series: kafka_status
    # Sélecteur corrigé pour cibler le <path> à l'intérieur du groupe
    selector: '[data-cell-id="z0Z9Q-BWpyTF2NEFeLIu-19"] path'
    thresholds:
      - { value: 0, color: '#F2495C' } # Rouge
      - { value: 1, color: '#73BF69' } # Vert

  # Règle pour le NOMBRE DE TOPICS (texte)
  - type: series-to-text
    series: kafka_total_topics
    # On cible un des chemins dans l'icône
    selector: '[data-cell-id="z0Z9Q-BWpyTF2NEFeLIu-19"] path:nth-of-type(2)'
    text:
      x: 39      # Coordonnées ajustées pour le centre de l'icône Kafka
      y: 322
      'text-anchor': middle
      'font-size': '14px'
      fill: 'white'
    prefix: 'Topics: '
    value: current-formatted

  # Règle pour le NOMBRE DE MESSAGES (texte)
  - type: series-to-text
    series: kafka_total_messages
    selector: '[data-cell-id="z0Z9Q-BWpyTF2NEFeLIu-19"] path:nth-of-type(3)'
    text:
      x: 39
      y: 350
      'text-anchor': middle
      'font-size': '14px'
      fill: 'white'
    prefix: 'Msg: '
    value: current-formatted # Utilise la valeur formatée (avec k, M, etc.)
